// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMC6AUOzzMiWMS3-G94VK76UohQ4ivWJk',
    appId: '1:921950633809:web:5bef7c0c6cb88f5d21dd70',
    messagingSenderId: '921950633809',
    projectId: 'spottr-2b5c1',
    authDomain: 'spottr-2b5c1.firebaseapp.com',
    storageBucket: 'spottr-2b5c1.firebasestorage.app',
    measurementId: 'G-EKH9ST6JLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmKGaL7huovlEWkgLDk10u6nwqiWZb7qQ',
    appId: '1:921950633809:android:376621c5aba67ad121dd70',
    messagingSenderId: '921950633809',
    projectId: 'spottr-2b5c1',
    storageBucket: 'spottr-2b5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-sA4z6My8DDoWsbJ_qBgydhn5BO2Bj50',
    appId: '1:921950633809:ios:895e97d0c340f3a521dd70',
    messagingSenderId: '921950633809',
    projectId: 'spottr-2b5c1',
    storageBucket: 'spottr-2b5c1.firebasestorage.app',
    iosBundleId: 'com.example.tryingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-sA4z6My8DDoWsbJ_qBgydhn5BO2Bj50',
    appId: '1:921950633809:ios:895e97d0c340f3a521dd70',
    messagingSenderId: '921950633809',
    projectId: 'spottr-2b5c1',
    storageBucket: 'spottr-2b5c1.firebasestorage.app',
    iosBundleId: 'com.example.tryingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMC6AUOzzMiWMS3-G94VK76UohQ4ivWJk',
    appId: '1:921950633809:web:3c09b91f6d8eac9521dd70',
    messagingSenderId: '921950633809',
    projectId: 'spottr-2b5c1',
    authDomain: 'spottr-2b5c1.firebaseapp.com',
    storageBucket: 'spottr-2b5c1.firebasestorage.app',
    measurementId: 'G-Q7TSJTKKP6',
  );

}